from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import numpy as np
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure

class QLabelFramed(QtWidgets.QLabel):
    def __init__(self, parent=None):
        super(QLabelFramed, self).__init__(parent)
        self.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

class ManualControlWidget(QtWidgets.QWidget):
    def __init__(self, parent=None, coordinate = '_'):
        super(ManualControlWidget, self).__init__(parent)
        layout = QtWidgets.QGridLayout()

        self.radioButton = QtWidgets.QRadioButton(parent=parent)
        self.step_label = QtWidgets.QLabel(parent=parent)
        self.step_textEdit = QtWidgets.QLineEdit(parent=parent)
        self.step_textEdit.setMaximumSize(QtCore.QSize(40, 30))
        self.horizontalSlider = QtWidgets.QSlider(parent=parent)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.man_label = QtWidgets.QLabel(parent=parent)
        self.man_textEdit = QtWidgets.QLineEdit(parent=parent)
        self.man_textEdit.setMaximumSize(QtCore.QSize(60, 30))
        self.pos_fdbk_label = QLabelFramed(parent=parent)
        self.dlabel = QtWidgets.QLabel(parent=parent)
        self.dfdbk_label = QtWidgets.QLabel(parent=parent)
        self.dfdbk_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dfdbk_label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.dfdbk_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.step_label.setText(f"s{coordinate}")
        self.man_label.setText(f"{coordinate}man")
        self.pos_fdbk_label.setText("TextLabel")
        self.dfdbk_label.setText("TextLabel")
        self.radioButton.setText(coordinate)
        self.dlabel.setText("d"+coordinate)

        layout.addWidget(self.radioButton, 0, 0, 1, 1)
        layout.addWidget(self.step_label, 0, 1, 1, 1)
        layout.addWidget(self.step_textEdit, 0, 2, 1, 1)
        layout.addWidget(self.horizontalSlider, 0, 3, 1, 1)
        layout.addWidget(self.man_label, 0, 4, 1, 1)
        layout.addWidget(self.man_textEdit, 0, 5, 1, 1)
        layout.addWidget(self.pos_fdbk_label, 0, 6, 1, 1)
        layout.addWidget(self.dlabel, 0, 7, 1, 1)
        layout.addWidget(self.dfdbk_label, 0, 8, 1, 1)

        self.radioButton.toggled.connect(self.radio_button_check)
        self.man_textEdit.returnPressed.connect(lambda: self.set_slider(self.man_textEdit, self.horizontalSlider))
        self.horizontalSlider.valueChanged.connect(self.slider_changed)
        # self.man_textEdit.textChanged.connect(lambda : print(self.man_textEdit.text()))

        self.setLayout(layout)

        self.widget_touple = (self.radioButton,
        self.step_label,
        self.step_textEdit,
        self.horizontalSlider,
        self.man_label,
        self.man_textEdit,
        self.pos_fdbk_label,
        self.dlabel,
        self.dfdbk_label)

        for w in self.widget_touple[1:]:
            w.setEnabled(False)
        
    def getwidgets(self):
        return self.widget_touple

    def radio_button_check(self):
        for w in self.widget_touple[1:]:
            w.setEnabled(self.widget_touple[0].isChecked())

    def set_slider(self, textfield, slider):
        try:
            value = int(float(textfield.text()) * 10)

            if value < slider.minimum() or value > slider.maximum():
                print(f"Value out of bounds, snapped to {'minimum' if value < slider.minimum() else 'maximum'}")
            slider.setValue(value)
        except ValueError:
            print('Inputted value is not a floating point number')

    def slider_changed(self):
        self.new_val = self.horizontalSlider.value() / 10
        self.man_textEdit.setText(str(self.new_val))

class ScanParametersWidget(QtWidgets.QWidget):
    def __init__(self, parent=None, coordinate = '_'):
        super(ScanParametersWidget, self).__init__(parent)
        self.xyzS_params_VLayout = QtWidgets.QVBoxLayout(self)
        self.xyzS_params_label = QtWidgets.QLabel(parent=self)
        self.xyzS_params_label.setMaximumHeight(30)
        self.xyzS_params_label.setStyleSheet("font-weight: bold")
        self.xyzS_params_label.setText("Scan Parameters")
        # self.xyzS_params_label.setSizePolicy(QtWidgets.QSizePolicy.)

        self.x0_label = QtWidgets.QLabel(parent=self)
        self.y0_label = QtWidgets.QLabel(parent=self)
        self.z0_label = QtWidgets.QLabel(parent=self)
        self.x0_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.y0_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.z0_lineEdit = QtWidgets.QLineEdit(parent=self)

        self.a0_label = QtWidgets.QLabel(parent=self)
        self.b0_label = QtWidgets.QLabel(parent=self)
        self.c0_label = QtWidgets.QLabel(parent=self)
        self.a0_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.b0_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.c0_lineEdit = QtWidgets.QLineEdit(parent=self)

        self.x1min_label = QtWidgets.QLabel(parent=self)
        self.x1max_label = QtWidgets.QLabel(parent=self)
        self.x1step_label = QtWidgets.QLabel(parent=self)
        self.x1min_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.x1max_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.x1step_lineEdit = QtWidgets.QLineEdit(parent=self)

        self.x2min_label = QtWidgets.QLabel(parent=self)
        self.x2max_label = QtWidgets.QLabel(parent=self)
        self.x2step_label = QtWidgets.QLabel(parent=self)
        self.x2min_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.x2max_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.x2step_lineEdit = QtWidgets.QLineEdit(parent=self)

        self.x3min_label = QtWidgets.QLabel(parent=self)
        self.x3max_label = QtWidgets.QLabel(parent=self)
        self.x3step_label = QtWidgets.QLabel(parent=self)
        self.x3min_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.x3max_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.x3step_lineEdit = QtWidgets.QLineEdit(parent=self)

        self.origin_params_w_list = [self.x0_label,self.x0_lineEdit,
                                     self.y0_label,self.y0_lineEdit,
                                     self.z0_label,self.z0_lineEdit]

        self.orientation_params_w_list = [self.a0_label, self.a0_lineEdit,
                                     self.b0_label, self.b0_lineEdit,
                                     self.c0_label, self.c0_lineEdit]
        self.x1_params_w_list = [self.x1min_label, self.x1min_lineEdit,
                                     self.x1max_label, self.x1max_lineEdit,
                                     self.x1step_label, self.x1step_lineEdit]
        self.x2_params_w_list = [self.x2min_label, self.x2min_lineEdit,
                                     self.x2max_label, self.x2max_lineEdit,
                                     self.x2step_label, self.x2step_lineEdit]
        self.x3_params_w_list = [self.x3min_label, self.x3min_lineEdit,
                                     self.x3max_label, self.x3max_lineEdit,
                                     self.x3step_label, self.x3step_lineEdit]

        self.params_rows = [self.origin_params_w_list,self.orientation_params_w_list,
                            self.x1_params_w_list,self.x2_params_w_list,self.x3_params_w_list]

        self.xyzS_params_gridLayout = QtWidgets.QGridLayout()
        for ir, r in enumerate(self.params_rows):
            for iw, w in enumerate(r):
                self.xyzS_params_gridLayout.addWidget(w, ir, iw, 1, 1)

        self.scan_types = ["XYZ scan","Spherical scan"]
        self.scan_type_combobox = QtWidgets.QComboBox(parent=self)
        self.scan_type_combobox.addItems(self.scan_types)
        self.scan_type_combobox.currentTextChanged.connect(lambda: self.set_scan(self.scan_type_combobox.currentText()))



        self.xyzS_params_VLayout.addWidget(self.xyzS_params_label)
        self.xyzS_params_VLayout.addLayout(self.xyzS_params_gridLayout)
        self.xyzS_params_VLayout.addWidget(self.scan_type_combobox)

        self.set_scan("XYZ scan")

    def set_scan(self,scan_type):
        if scan_type == "XYZ scan":
            for iw, w in enumerate(self.origin_params_w_list[::2]):
                w.setText(["X0","Y0","Z0"][iw])
                coordinates = ["X", "Y", "Z"]
        if scan_type == "Spherical scan":
            for iw, w in enumerate(self.origin_params_w_list[::2]):
                w.setText(["Xc","Yc","Zc"][iw])
                coordinates = ["R", "φ", "θ"]

        for iw, w in enumerate(self.params_rows[1][::2]):
            w.setText(["A0", "B0", "C0"][iw])
        
        for ir, row in enumerate(self.params_rows[2:]):
            for iw, w in enumerate(row[::2]):
                w.setText(["{}max", "{}min", "{}step"][iw].format(coordinates[ir]))

        if scan_type == "Spherical scan":
            self.params_rows[2][0].setText(coordinates[0])
            for w in self.params_rows[2][2:]:
                w.setVisible(False)
                w.sizePolicy().setRetainSizeWhenHidden(True)
        else:
            for w in self.params_rows[2][2:]:
                w.setVisible(True)






class MainWindow(QtWidgets.QMainWindow):
    def __init__(self, *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)

    def initialize_connectionTab(self):
        connectionTab = QtWidgets.QWidget()

        self.gridLayout_3 = QtWidgets.QGridLayout(connectionTab)
        self.connection_main_HLayout = QtWidgets.QHBoxLayout(connectionTab)
        self.gridLayout_3.addLayout(self.connection_main_HLayout, 0, 0, 1, 1)

        self.con_params_gridLayout = QtWidgets.QGridLayout()

        self.robot_port_lineEdit = QtWidgets.QLineEdit(parent=connectionTab)
        self.cont_vna_pushButton = QtWidgets.QPushButton(parent=connectionTab)
        self.ping_robot_pushButton = QtWidgets.QPushButton(parent=connectionTab)
        self.robot_ip_label = QtWidgets.QLabel(parent=connectionTab)
        self.con_robot_pushButton = QtWidgets.QPushButton(parent=connectionTab)
        self.con_stop_pushButton = QtWidgets.QPushButton(parent=connectionTab)
        self.vna_port_lineEdit = QtWidgets.QLineEdit(parent=connectionTab)
        self.vna_ip_label = QtWidgets.QLabel(parent=connectionTab)
        self.vna_port_label = QtWidgets.QLabel(parent=connectionTab)
        self.robot_ip_lineEdit = QtWidgets.QLineEdit(parent=connectionTab)
        self.ping_vna_pushButton = QtWidgets.QPushButton(parent=connectionTab)
        self.disconnect_pushButton = QtWidgets.QPushButton(parent=connectionTab)
        self.vna_ip_lineEdit = QtWidgets.QLineEdit(parent=connectionTab)
        self.robot_port_label = QtWidgets.QLabel(parent=connectionTab)

        self.con_stop_pushButton.setStyleSheet("font-weight: bold")

        self.con_params_gridLayout.addWidget(self.robot_port_lineEdit, 1, 2, 1, 1)
        self.con_params_gridLayout.addWidget(self.cont_vna_pushButton, 5, 1, 1, 1)
        self.con_params_gridLayout.addWidget(self.ping_robot_pushButton, 4, 0, 1, 1)
        self.con_params_gridLayout.addWidget(self.robot_ip_label, 0, 0, 1, 1)
        self.con_params_gridLayout.addWidget(self.con_robot_pushButton, 4, 1, 1, 1)
        self.con_params_gridLayout.addWidget(self.con_stop_pushButton, 6, 0, 1, 1)
        self.con_params_gridLayout.addWidget(self.vna_port_lineEdit, 3, 2, 1, 1)
        self.con_params_gridLayout.addWidget(self.vna_ip_label, 2, 0, 1, 1)
        self.con_params_gridLayout.addWidget(self.vna_port_label, 3, 0, 1, 1)
        self.con_params_gridLayout.addWidget(self.robot_ip_lineEdit, 0, 2, 1, 1)
        self.con_params_gridLayout.addWidget(self.ping_vna_pushButton, 5, 0, 1, 1)
        self.con_params_gridLayout.addWidget(self.disconnect_pushButton, 6, 1, 1, 1)
        self.con_params_gridLayout.addWidget(self.vna_ip_lineEdit, 2, 2, 1, 1)
        self.con_params_gridLayout.addWidget(self.robot_port_label, 1, 0, 1, 1)

        self.con_params_gridLayout.addItem(QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                                                 QtWidgets.QSizePolicy.Policy.Expanding), 7, 1, 1, 1)

        self.connection_main_HLayout.addLayout(self.con_params_gridLayout)
        self.con_log_gridLayout = QtWidgets.QGridLayout()
        self.connection_main_HLayout.addLayout(self.con_log_gridLayout)

        self.con_log_header_label = QtWidgets.QLabel(parent=connectionTab)
        self.con_log_textB = QtWidgets.QTextBrowser(parent=connectionTab)

        self.con_log_gridLayout.addWidget(self.con_log_header_label, 0, 0, 1, 1)
        self.con_log_gridLayout.addWidget(self.con_log_textB, 1, 0, 1, 1)
        return connectionTab

    def initialize_manualCTab(self):
        manualCTab = QtWidgets.QWidget()
        self.gridLayout_4 = QtWidgets.QGridLayout(manualCTab)
        self.man_main_VLayout = QtWidgets.QVBoxLayout()
        self.man_move_gridLayout = QtWidgets.QGridLayout()

        coordinates_list = ["X", "Y", "Z", "A", "B", "C", "T"]
        self.coordinates_widgets_list = []
        for ic, coord in enumerate(coordinates_list):
            setattr(self, f"manual_control_{coord}", ManualControlWidget(parent = manualCTab, coordinate= coord))
            self.coordinates_widgets_list.append(eval(f"self.manual_control_{coord}"))

        for ic, coord in enumerate(coordinates_list):
            for iw, widget in enumerate(self.coordinates_widgets_list[ic].getwidgets()):
                self.man_move_gridLayout.addWidget(widget, 1+ic,iw,1,1)

        self.man_select_label = QtWidgets.QLabel(parent=manualCTab)
        self.man_select_label.setStyleSheet("font-weight: bold")
        self.man_move_gridLayout.addWidget(self.man_select_label, 0, 0, 1, 1)
        self.man_select_label.setMaximumHeight(30)
        self.man_step_label = QtWidgets.QLabel(parent=manualCTab)
        self.man_step_label.setStyleSheet("font-weight: bold")
        self.man_move_gridLayout.addWidget(self.man_step_label, 0, 2, 1, 1)
        self.man_pos_label = QtWidgets.QLabel(parent=manualCTab)
        self.man_pos_label.setStyleSheet("font-weight: bold")
        self.man_move_gridLayout.addWidget(self.man_pos_label, 0, 3, 1, 1)
        self.man_input_label = QtWidgets.QLabel(parent=manualCTab)
        self.man_input_label.setStyleSheet("font-weight: bold")
        self.man_move_gridLayout.addWidget(self.man_input_label, 0, 5, 1, 1)
        self.man_pos_fdbk_label = QtWidgets.QLabel(parent=manualCTab)
        self.man_pos_fdbk_label.setStyleSheet("font-weight: bold")
        self.man_move_gridLayout.addWidget(self.man_pos_fdbk_label, 0, 6, 1, 1)
        self.man_pos_real_fdbk_label = QtWidgets.QLabel(parent=manualCTab)
        self.man_pos_real_fdbk_label.setStyleSheet("font-weight: bold")
        self.man_move_gridLayout.addWidget(self.man_pos_real_fdbk_label, 0, 8, 1, 1)

        self.man_step_label.setText("Step size")
        self.man_pos_label.setText("Position Selection")
        self.man_select_label.setText("Movement Selection")
        self.man_pos_fdbk_label.setText("Position feedback")
        self.man_pos_real_fdbk_label.setText("Position accuracy")
        self.man_input_label.setText("Manual In")


        self.man_main_VLayout.addLayout(self.man_move_gridLayout)
        self.man_stop_pushButton = QtWidgets.QPushButton(parent=manualCTab)
        self.man_stop_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))

        self.man_stop_pushButton.setStyleSheet("font-weight: bold")
        self.man_main_VLayout.addWidget(self.man_stop_pushButton)

        self.gridLayout_4.addLayout(self.man_main_VLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 1, 0, 1, 1)

        return manualCTab

    def initialize_XYZScanTab(self):
        xyzSTab = QtWidgets.QWidget()

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        self.gridLayout_6 = QtWidgets.QGridLayout(xyzSTab)
        self.xyzS_VLayout = QtWidgets.QVBoxLayout()
        self.xyzS_params_HLayout = QtWidgets.QHBoxLayout()
        self.xyzS_params_VLayout = QtWidgets.QVBoxLayout()
        self.xyzS_params_VLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.xyzS_params_label = QtWidgets.QLabel(parent=xyzSTab)

        self.xyzS_params_label.setStyleSheet("font-weight: bold")
        self.xyzS_params_VLayout.addWidget(self.xyzS_params_label)
        self.xyzS_params_gridLayout = QtWidgets.QGridLayout()
        self.x0_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.x0_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.x0_xyzS_textEdit, 0, 1, 1, 1)
        self.ymax_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.ymax_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.ymax_xyzS_textEdit, 3, 3, 1, 1)
        self.xmin_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.xmin_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.xmin_xyzS_textEdit, 2, 1, 1, 1)
        self.x0_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.x0_xyzS_label, 0, 0, 1, 1)
        self.xmin_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.xmin_xyzS_label, 2, 0, 1, 1)
        self.xmax_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.xmax_xyzS_label, 2, 2, 1, 1)
        self.zmax_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.zmax_xyzS_label, 4, 2, 1, 1)
        self.xz0_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.xz0_xyzS_label, 0, 4, 1, 1)
        self.zstp_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.zstp_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.zstp_xyzS_textEdit, 4, 5, 1, 1)
        self.ymin_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.ymin_xyzS_label, 3, 0, 1, 1)
        self.zmax_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.zmax_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.zmax_xyzS_textEdit, 4, 3, 1, 1)
        self.ymax_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.ymax_xyzS_label, 3, 2, 1, 1)
        self.ystp_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.ystp_xyzS_label, 3, 4, 1, 1)
        self.xy0_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.xy0_xyzS_label, 0, 2, 1, 1)
        self.ymin_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.ymin_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.ymin_xyzS_textEdit, 3, 1, 1, 1)
        self.xstp_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.xstp_xyzS_label, 2, 4, 1, 1)
        self.zmin_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.zmin_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.zmin_xyzS_textEdit, 4, 1, 1, 1)
        self.zmin_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.zmin_xyzS_label, 4, 0, 1, 1)
        self.y0_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.y0_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.y0_xyzS_textEdit, 0, 3, 1, 1)
        self.ystp_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.ystp_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.ystp_xyzS_textEdit, 3, 5, 1, 1)
        self.z0_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.z0_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.z0_xyzS_textEdit, 0, 5, 1, 1)
        self.xstp_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.xstp_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.xstp_xyzS_textEdit, 2, 5, 1, 1)
        self.zstp_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.zstp_xyzS_label, 4, 4, 1, 1)
        self.xmax_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.xmax_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.xmax_xyzS_textEdit, 2, 3, 1, 1)
        self.a0_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.a0_xyzS_label, 1, 0, 1, 1)
        self.b0_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.b0_xyzS_label, 1, 2, 1, 1)
        self.c0_xyzS_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_params_gridLayout.addWidget(self.c0_xyzS_label, 1, 4, 1, 1)
        self.a0_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.a0_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.a0_xyzS_textEdit, 1, 1, 1, 1)
        self.b0_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.b0_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.b0_xyzS_textEdit, 1, 3, 1, 1)
        self.c0_xyzS_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.c0_xyzS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_params_gridLayout.addWidget(self.c0_xyzS_textEdit, 1, 5, 1, 1)
        self.xyzS_params_VLayout.addLayout(self.xyzS_params_gridLayout)
        self.xyzS_datapath_HLayout = QtWidgets.QHBoxLayout()

        self.xyzS_datapath_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_datapath_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_datapath_HLayout.addWidget(self.xyzS_datapath_label)
        self.xyzS_datapath_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.xyzS_datapath_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xyzS_datapath_HLayout.addWidget(self.xyzS_datapath_textEdit)
        self.xpol_xyzS_params_checkBox = QtWidgets.QCheckBox(parent=xyzSTab)
        self.xyzS_datapath_HLayout.addWidget(self.xpol_xyzS_params_checkBox)
        self.xyzS_datapath_toolButton = QtWidgets.QToolButton(parent=xyzSTab)
        self.xyzS_datapath_HLayout.addWidget(self.xyzS_datapath_toolButton)
        self.xyzS_params_VLayout.addLayout(self.xyzS_datapath_HLayout)
        self.xyzS_params_HLayout.addLayout(self.xyzS_params_VLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.xyzS_params_HLayout.addItem(spacerItem2)
        self.xyzS_VLayout.addLayout(self.xyzS_params_HLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.xyzS_VLayout.addItem(spacerItem3)
        self.xyzS_vna_VLayout = QtWidgets.QVBoxLayout()
        self.xyzS_vna_label = QtWidgets.QLabel(parent=xyzSTab)

        self.xyzS_vna_label.setStyleSheet("font-weight: bold")
        self.xyzS_vna_VLayout.addWidget(self.xyzS_vna_label)
        self.xyzS_vna_gridLayout = QtWidgets.QGridLayout()
        self.ifbw_xyzS_vna_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_vna_gridLayout.addWidget(self.ifbw_xyzS_vna_label, 0, 0, 1, 1)
        self.ab_xyzS_vna_checkBox = QtWidgets.QCheckBox(parent=xyzSTab)
        self.xyzS_vna_gridLayout.addWidget(self.ab_xyzS_vna_checkBox, 1, 4, 1, 1)
        self.ifbw_xyzS_vna_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.ifbw_xyzS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.xyzS_vna_gridLayout.addWidget(self.ifbw_xyzS_vna_textEdit, 0, 1, 1, 1)
        self.sttl_xyzS_vna_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_vna_gridLayout.addWidget(self.sttl_xyzS_vna_label, 1, 2, 1, 1)
        self.attn_xyzS_vna_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_vna_gridLayout.addWidget(self.attn_xyzS_vna_label, 1, 0, 1, 1)
        self.fmin_xyzS_vna_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_vna_gridLayout.addWidget(self.fmin_xyzS_vna_label, 0, 2, 1, 1)
        self.fmax_xyzS_vna_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_vna_gridLayout.addWidget(self.fmax_xyzS_vna_label, 0, 4, 1, 1)
        self.fmax_xyzS_vna_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.fmax_xyzS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.xyzS_vna_gridLayout.addWidget(self.fmax_xyzS_vna_textEdit, 0, 5, 1, 1)
        self.fstp_xyzS_vna_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.fstp_xyzS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.xyzS_vna_gridLayout.addWidget(self.fstp_xyzS_vna_textEdit, 0, 7, 1, 1)
        self.sttl_xyzS_vna_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.sttl_xyzS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.xyzS_vna_gridLayout.addWidget(self.sttl_xyzS_vna_textEdit, 1, 3, 1, 1)
        self.xyzS_vna_pushButton = QtWidgets.QPushButton(parent=xyzSTab)
        self.xyzS_vna_gridLayout.addWidget(self.xyzS_vna_pushButton, 1, 7, 1, 1)
        self.attn_xyzS_vna_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.attn_xyzS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.xyzS_vna_gridLayout.addWidget(self.attn_xyzS_vna_textEdit, 1, 1, 1, 1)
        self.fwbw_xyzS_vna_checkBox = QtWidgets.QCheckBox(parent=xyzSTab)
        self.xyzS_vna_gridLayout.addWidget(self.fwbw_xyzS_vna_checkBox, 1, 5, 1, 1)
        self.fstp_xyzS_vna_label = QtWidgets.QLabel(parent=xyzSTab)
        self.xyzS_vna_gridLayout.addWidget(self.fstp_xyzS_vna_label, 0, 6, 1, 1)
        self.fmin_xyzS_vna_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.fmin_xyzS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.xyzS_vna_gridLayout.addWidget(self.fmin_xyzS_vna_textEdit, 0, 3, 1, 1)
        self.xyzS_vna_VLayout.addLayout(self.xyzS_vna_gridLayout)
        self.xyzS_VLayout.addLayout(self.xyzS_vna_VLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.xyzS_VLayout.addItem(spacerItem4)
        self.xyzS_run_HLayout = QtWidgets.QHBoxLayout()
        self.xyzS_run_gridLayout = QtWidgets.QGridLayout()

        self.xyzS_run_pushButton = QtWidgets.QPushButton(parent=xyzSTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        self.xyzS_run_gridLayout.addWidget(self.xyzS_run_pushButton, 3, 0, 1, 1)
        self.xyzS_sim_pushButton = QtWidgets.QPushButton(parent=xyzSTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        self.xyzS_run_gridLayout.addWidget(self.xyzS_sim_pushButton, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.xyzS_run_gridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        self.xyzS_stop_pushButton = QtWidgets.QPushButton(parent=xyzSTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)

        self.xyzS_stop_pushButton.setStyleSheet("font-weight: bold")
        self.xyzS_run_gridLayout.addWidget(self.xyzS_stop_pushButton, 4, 0, 1, 1)
        self.xyzS_run_label = QtWidgets.QLabel(parent=xyzSTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)

        self.xyzS_run_label.setStyleSheet("font-weight: bold")
        self.xyzS_run_gridLayout.addWidget(self.xyzS_run_label, 0, 0, 1, 1)
        self.xyzS_run_HLayout.addLayout(self.xyzS_run_gridLayout)
        self.xyzS_fdbk_VLayout = QtWidgets.QVBoxLayout()
        self.xyzS_fdbk_label = QtWidgets.QLabel(parent=xyzSTab)

        self.xyzS_fdbk_label.setStyleSheet("font-weight: bold")
        self.xyzS_fdbk_VLayout.addWidget(self.xyzS_fdbk_label)
        self.xyzS_fdbk_gridLayout = QtWidgets.QGridLayout()
        self.z_xyzS_fdbk_label = QtWidgets.QLabel(parent=xyzSTab)
        self.z_xyzS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.xyzS_fdbk_gridLayout.addWidget(self.z_xyzS_fdbk_label, 0, 4, 1, 1)
        self.c_xyzS_fdbk_val_label = QtWidgets.QLabel(parent=xyzSTab)
        self.c_xyzS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.c_xyzS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.xyzS_fdbk_gridLayout.addWidget(self.c_xyzS_fdbk_val_label, 1, 5, 1, 1)
        self.y_xyzS_fdbk_val_label = QtWidgets.QLabel(parent=xyzSTab)
        self.y_xyzS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.y_xyzS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.xyzS_fdbk_gridLayout.addWidget(self.y_xyzS_fdbk_val_label, 0, 3, 1, 1)
        self.c_xyzS_fdbk_label = QtWidgets.QLabel(parent=xyzSTab)
        self.c_xyzS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.xyzS_fdbk_gridLayout.addWidget(self.c_xyzS_fdbk_label, 1, 4, 1, 1)
        self.x_xyzS_fdbk_label = QtWidgets.QLabel(parent=xyzSTab)
        self.x_xyzS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.xyzS_fdbk_gridLayout.addWidget(self.x_xyzS_fdbk_label, 0, 0, 1, 1)
        self.z_xyzS_fdbk_val_label = QtWidgets.QLabel(parent=xyzSTab)
        self.z_xyzS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.z_xyzS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.xyzS_fdbk_gridLayout.addWidget(self.z_xyzS_fdbk_val_label, 0, 5, 1, 1)
        self.y_xyzS_fdbk_label = QtWidgets.QLabel(parent=xyzSTab)
        self.y_xyzS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.xyzS_fdbk_gridLayout.addWidget(self.y_xyzS_fdbk_label, 0, 2, 1, 1)
        self.b_xyzS_fdbk_label = QtWidgets.QLabel(parent=xyzSTab)
        self.b_xyzS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.xyzS_fdbk_gridLayout.addWidget(self.b_xyzS_fdbk_label, 1, 2, 1, 1)
        self.a_xyzS_fdbk_val_label = QtWidgets.QLabel(parent=xyzSTab)
        self.a_xyzS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.a_xyzS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.xyzS_fdbk_gridLayout.addWidget(self.a_xyzS_fdbk_val_label, 1, 1, 1, 1)
        self.a_xyzS_fdbk_label = QtWidgets.QLabel(parent=xyzSTab)
        self.a_xyzS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.xyzS_fdbk_gridLayout.addWidget(self.a_xyzS_fdbk_label, 1, 0, 1, 1)
        self.b_xyzS_fdbk_val_label = QtWidgets.QLabel(parent=xyzSTab)
        self.b_xyzS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.b_xyzS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.xyzS_fdbk_gridLayout.addWidget(self.b_xyzS_fdbk_val_label, 1, 3, 1, 1)
        self.x_xyzS_fdbk_val_label = QtWidgets.QLabel(parent=xyzSTab)
        self.x_xyzS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.x_xyzS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.xyzS_fdbk_gridLayout.addWidget(self.x_xyzS_fdbk_val_label, 0, 1, 1, 1)
        self.xyzS_fdbk_VLayout.addLayout(self.xyzS_fdbk_gridLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.xyzS_fdbk_VLayout.addItem(spacerItem6)
        self.xyzS_run_HLayout.addLayout(self.xyzS_fdbk_VLayout)
        self.xyzS_log_VLayout = QtWidgets.QVBoxLayout()

        self.xyzS_log_label = QtWidgets.QLabel(parent=xyzSTab)

        self.xyzS_log_label.setStyleSheet("font-weight: bold")
        self.xyzS_log_VLayout.addWidget(self.xyzS_log_label)
        self.xyzS_log_textEdit = QtWidgets.QTextEdit(parent=xyzSTab)
        self.xyzS_log_textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.xyzS_log_VLayout.addWidget(self.xyzS_log_textEdit)
        self.xyzS_run_HLayout.addLayout(self.xyzS_log_VLayout)
        self.xyzS_VLayout.addLayout(self.xyzS_run_HLayout)
        self.gridLayout_6.addLayout(self.xyzS_VLayout, 0, 0, 1, 1)

        return xyzSTab

    def initialize_scanTab(self):
        scan_tab = QtWidgets.QWidget()
        self.gridLayout_6 = QtWidgets.QGridLayout(scan_tab)
        self.xyzS_VLayout = QtWidgets.QVBoxLayout()
        self.scan_parameters_widget = ScanParametersWidget(scan_tab)
        self.xyzS_VLayout.addWidget(self.scan_parameters_widget)
        self.gridLayout_6.addLayout(self.xyzS_VLayout,0,0,1,1)


        return scan_tab
            


    def test(self):
        print("this works")
        
    def setupUi(self, MainWindow):
        # MainWindow.resize(1624, 791)

        self.figure = Figure(figsize=(5, 4), dpi=100)
        self.canvas = FigureCanvas(self.figure)
        self.toolbar = NavigationToolbar(self.canvas, self)

        MainWindow.setDockOptions(QtWidgets.QMainWindow.DockOption.AllowTabbedDocks|QtWidgets.QMainWindow.DockOption.AnimatedDocks|QtWidgets.QMainWindow.DockOption.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)

        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.mainGridLayout = QtWidgets.QGridLayout()

        self.mainTabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)

        self.connectionTab = self.initialize_connectionTab()
        self.mainTabWidget.addTab(self.connectionTab, "")

        self.manualCTab = self.initialize_manualCTab()
        self.mainTabWidget.addTab(self.manualCTab, "")

        self.scanTab = self.initialize_scanTab()
        self.mainTabWidget.addTab(self.scanTab, "")

        self.xyzSTab = self.initialize_XYZScanTab()
        self.mainTabWidget.addTab(self.xyzSTab, "")


        self.mainTabWidget.addTab(self.xyzSTab, "")
        self.sphericalSTab = QtWidgets.QWidget()
        self.gridLayout_5 = QtWidgets.QGridLayout(self.sphericalSTab)
        self.sphS_VLayout = QtWidgets.QVBoxLayout()
        self.sphS_params_HLayout = QtWidgets.QHBoxLayout()
        self.sphS_params_VLayout = QtWidgets.QVBoxLayout()
        self.sphS_params_VLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.sphS_params_label = QtWidgets.QLabel(parent=self.sphericalSTab)

        self.sphS_params_label.setStyleSheet("font-weight: bold")
        self.sphS_params_VLayout.addWidget(self.sphS_params_label)
        self.sphS_params_gridLayout = QtWidgets.QGridLayout()
        self.yc_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.yc_sphS_label, 0, 2, 1, 1)
        self.phmax_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.phmax_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.phmax_sphS_textEdit, 4, 3, 1, 1)
        self.thstp_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.thstp_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.thstp_sphS_textEdit, 3, 5, 1, 1)
        self.phstp_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.phstp_sphS_label, 4, 4, 1, 1)
        self.a0_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.a0_sphS_label, 1, 0, 1, 1)
        self.r_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.r_sphS_label, 2, 0, 1, 1)
        self.thmax_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.thmax_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.thmax_sphS_textEdit, 3, 3, 1, 1)
        self.zc_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.zc_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.zc_sphS_textEdit, 0, 5, 1, 1)
        self.phstp_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.phstp_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.phstp_sphS_textEdit, 4, 5, 1, 1)
        self.thmin_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.thmin_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.thmin_sphS_textEdit, 3, 1, 1, 1)
        self.b0_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.b0_sphS_label, 1, 2, 1, 1)
        self.thmin_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.thmin_sphS_label, 3, 0, 1, 1)
        self.c0_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.c0_sphS_label, 1, 4, 1, 1)
        self.r_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.r_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.r_sphS_textEdit, 2, 1, 1, 1)
        self.thmax_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.thmax_sphS_label, 3, 2, 1, 1)
        self.zc_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.zc_sphS_label, 0, 4, 1, 1)
        self.phmin_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.phmin_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.phmin_sphS_textEdit, 4, 1, 1, 1)
        self.xc_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.xc_sphS_label, 0, 0, 1, 1)
        self.b0_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.b0_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.b0_sphS_textEdit, 1, 3, 1, 1)
        self.phmin_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.phmin_sphS_label, 4, 0, 1, 1)
        self.phmax_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.phmax_sphS_label, 4, 2, 1, 1)
        self.xc_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.xc_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.xc_sphS_textEdit, 0, 1, 1, 1)
        self.a0_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.a0_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.a0_sphS_textEdit, 1, 1, 1, 1)
        self.yc_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.yc_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.yc_sphS_textEdit, 0, 3, 1, 1)
        self.c0_sphS_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.c0_sphS_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_params_gridLayout.addWidget(self.c0_sphS_textEdit, 1, 5, 1, 1)
        self.thstp_sphS_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_params_gridLayout.addWidget(self.thstp_sphS_label, 3, 4, 1, 1)
        self.sphS_params_VLayout.addLayout(self.sphS_params_gridLayout)
        self.sphS_datapath_HLayout = QtWidgets.QHBoxLayout()

        self.sphS_datapath_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_datapath_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_datapath_HLayout.addWidget(self.sphS_datapath_label)
        self.sphS_datapath_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.sphS_datapath_textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sphS_datapath_HLayout.addWidget(self.sphS_datapath_textEdit)
        self.xpol_sphS_params_checkBox_2 = QtWidgets.QCheckBox(parent=self.sphericalSTab)
        self.sphS_datapath_HLayout.addWidget(self.xpol_sphS_params_checkBox_2)
        self.sphS_datapath_toolButton = QtWidgets.QToolButton(parent=self.sphericalSTab)
        self.sphS_datapath_HLayout.addWidget(self.sphS_datapath_toolButton)
        self.sphS_params_VLayout.addLayout(self.sphS_datapath_HLayout)
        self.sphS_params_HLayout.addLayout(self.sphS_params_VLayout)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.sphS_params_HLayout.addItem(spacerItem7)
        self.sphS_VLayout.addLayout(self.sphS_params_HLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.sphS_VLayout.addItem(spacerItem8)
        self.sphS_vna_VLayout = QtWidgets.QVBoxLayout()
        self.sphS_vna_label = QtWidgets.QLabel(parent=self.sphericalSTab)

        self.sphS_vna_label.setStyleSheet("font-weight: bold")
        self.sphS_vna_VLayout.addWidget(self.sphS_vna_label)
        self.sphS_vna_gridLayout = QtWidgets.QGridLayout()
        self.ab_sphS_vna_checkBox = QtWidgets.QCheckBox(parent=self.sphericalSTab)
        self.sphS_vna_gridLayout.addWidget(self.ab_sphS_vna_checkBox, 1, 4, 1, 1)
        self.fwbw_sphS_vna_checkBox = QtWidgets.QCheckBox(parent=self.sphericalSTab)
        self.sphS_vna_gridLayout.addWidget(self.fwbw_sphS_vna_checkBox, 1, 5, 1, 1)
        self.fmin_sphS_vna_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_vna_gridLayout.addWidget(self.fmin_sphS_vna_label, 0, 2, 1, 1)
        self.fmax_sphS_vna_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_vna_gridLayout.addWidget(self.fmax_sphS_vna_label, 0, 4, 1, 1)
        self.fmin_sphS_vna_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.fmin_sphS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.sphS_vna_gridLayout.addWidget(self.fmin_sphS_vna_textEdit, 0, 3, 1, 1)
        self.fmax_sphS_vna_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.fmax_sphS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.sphS_vna_gridLayout.addWidget(self.fmax_sphS_vna_textEdit, 0, 5, 1, 1)
        self.fstp_sphS_vna_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_vna_gridLayout.addWidget(self.fstp_sphS_vna_label, 0, 6, 1, 1)
        self.sttln_sphS_vna_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.sttln_sphS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.sphS_vna_gridLayout.addWidget(self.sttln_sphS_vna_textEdit, 1, 3, 1, 1)
        self.fstp_sphS_vna_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.fstp_sphS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.sphS_vna_gridLayout.addWidget(self.fstp_sphS_vna_textEdit, 0, 7, 1, 1)
        self.sphS_vna_pushButton = QtWidgets.QPushButton(parent=self.sphericalSTab)
        self.sphS_vna_gridLayout.addWidget(self.sphS_vna_pushButton, 1, 7, 1, 1)
        self.ifbw_sphS_vna_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_vna_gridLayout.addWidget(self.ifbw_sphS_vna_label, 0, 0, 1, 1)
        self.attn_sphS_vna_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_vna_gridLayout.addWidget(self.attn_sphS_vna_label, 1, 0, 1, 1)
        self.sttln_sphS_vna_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.sphS_vna_gridLayout.addWidget(self.sttln_sphS_vna_label, 1, 2, 1, 1)
        self.ifbw_sphS_vna_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.ifbw_sphS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.sphS_vna_gridLayout.addWidget(self.ifbw_sphS_vna_textEdit, 0, 1, 1, 1)
        self.attn_sphS_vna_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.attn_sphS_vna_textEdit.setMaximumSize(QtCore.QSize(80, 30))
        self.sphS_vna_gridLayout.addWidget(self.attn_sphS_vna_textEdit, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.sphS_vna_gridLayout.addItem(spacerItem9, 0, 8, 1, 1)
        self.sphS_vna_VLayout.addLayout(self.sphS_vna_gridLayout)
        self.sphS_VLayout.addLayout(self.sphS_vna_VLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.sphS_VLayout.addItem(spacerItem10)
        self.sphS_run_HLayout = QtWidgets.QHBoxLayout()
        self.sphS_run_gridLayout = QtWidgets.QGridLayout()

        self.sphS_run_pushButton = QtWidgets.QPushButton(parent=self.sphericalSTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        self.sphS_run_pushButton.setCheckable(False)
        self.sphS_run_pushButton.setAutoDefault(False)
        self.sphS_run_pushButton.setDefault(False)
        self.sphS_run_gridLayout.addWidget(self.sphS_run_pushButton, 3, 0, 1, 1)
        self.sphS_sim_pushButton = QtWidgets.QPushButton(parent=self.sphericalSTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        self.sphS_run_gridLayout.addWidget(self.sphS_sim_pushButton, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.sphS_run_gridLayout.addItem(spacerItem11, 1, 0, 1, 1)
        self.sphS_stop_pushButton = QtWidgets.QPushButton(parent=self.sphericalSTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)

        self.sphS_stop_pushButton.setStyleSheet("font-weight: bold")
        self.sphS_run_gridLayout.addWidget(self.sphS_stop_pushButton, 4, 0, 1, 1)
        self.sphS_run_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)

        self.sphS_run_label.setStyleSheet("font-weight: bold")
        self.sphS_run_gridLayout.addWidget(self.sphS_run_label, 0, 0, 1, 1)
        self.sphS_run_HLayout.addLayout(self.sphS_run_gridLayout)
        self.sphS_fdbk_VLayout = QtWidgets.QVBoxLayout()
        self.sphS_fdbk_label = QtWidgets.QLabel(parent=self.sphericalSTab)

        self.sphS_fdbk_label.setStyleSheet("font-weight: bold")
        self.sphS_fdbk_VLayout.addWidget(self.sphS_fdbk_label)
        self.sphS_fdbk_gridLayout = QtWidgets.QGridLayout()
        self.y_sphS_fdbk_val_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.y_sphS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.y_sphS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sphS_fdbk_gridLayout.addWidget(self.y_sphS_fdbk_val_label, 0, 3, 1, 1)
        self.x_sphS_fdbk_val_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.x_sphS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.x_sphS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sphS_fdbk_gridLayout.addWidget(self.x_sphS_fdbk_val_label, 0, 1, 1, 1)
        self.x_sphS_fdbk_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.x_sphS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.sphS_fdbk_gridLayout.addWidget(self.x_sphS_fdbk_label, 0, 0, 1, 1)
        self.a_sphS_fdbk_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.a_sphS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.sphS_fdbk_gridLayout.addWidget(self.a_sphS_fdbk_label, 1, 0, 1, 1)
        self.b_sphS_fdbk_val_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.b_sphS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.b_sphS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sphS_fdbk_gridLayout.addWidget(self.b_sphS_fdbk_val_label, 1, 3, 1, 1)
        self.z_sphS_fdbk_val_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.z_sphS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.z_sphS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sphS_fdbk_gridLayout.addWidget(self.z_sphS_fdbk_val_label, 0, 5, 1, 1)
        self.b_sphS_fdbk_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.b_sphS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.sphS_fdbk_gridLayout.addWidget(self.b_sphS_fdbk_label, 1, 2, 1, 1)
        self.c_sphS_fdbk_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.c_sphS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.sphS_fdbk_gridLayout.addWidget(self.c_sphS_fdbk_label, 1, 4, 1, 1)
        self.z_sphS_fdbk_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.z_sphS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.sphS_fdbk_gridLayout.addWidget(self.z_sphS_fdbk_label, 0, 4, 1, 1)
        self.c_sphS_fdbk_val_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.c_sphS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.c_sphS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sphS_fdbk_gridLayout.addWidget(self.c_sphS_fdbk_val_label, 1, 5, 1, 1)
        self.a_sphS_fdbk_val_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.a_sphS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.a_sphS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sphS_fdbk_gridLayout.addWidget(self.a_sphS_fdbk_val_label, 1, 1, 1, 1)
        self.y_sphS_fdbk_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.y_sphS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.sphS_fdbk_gridLayout.addWidget(self.y_sphS_fdbk_label, 0, 2, 1, 1)
        self.r_sphS_fdbk_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.r_sphS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.sphS_fdbk_gridLayout.addWidget(self.r_sphS_fdbk_label, 2, 0, 1, 1)
        self.r_sphS_fdbk_val_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.r_sphS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.r_sphS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sphS_fdbk_gridLayout.addWidget(self.r_sphS_fdbk_val_label, 2, 1, 1, 1)
        self.th_sphS_fdbk_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.th_sphS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.sphS_fdbk_gridLayout.addWidget(self.th_sphS_fdbk_label, 2, 2, 1, 1)
        self.th_sphS_fdbk_val_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.th_sphS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.th_sphS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sphS_fdbk_gridLayout.addWidget(self.th_sphS_fdbk_val_label, 2, 3, 1, 1)
        self.ph_sphS_fdbk_val_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.ph_sphS_fdbk_val_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ph_sphS_fdbk_val_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sphS_fdbk_gridLayout.addWidget(self.ph_sphS_fdbk_val_label, 2, 5, 1, 1)
        self.ph_sphS_fdbk_label = QtWidgets.QLabel(parent=self.sphericalSTab)
        self.ph_sphS_fdbk_label.setMaximumSize(QtCore.QSize(30, 30))
        self.sphS_fdbk_gridLayout.addWidget(self.ph_sphS_fdbk_label, 2, 4, 1, 1)
        self.sphS_fdbk_VLayout.addLayout(self.sphS_fdbk_gridLayout)
        spacerItem12 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.sphS_fdbk_VLayout.addItem(spacerItem12)
        self.sphS_run_HLayout.addLayout(self.sphS_fdbk_VLayout)
        self.sphS_log_VLayout = QtWidgets.QVBoxLayout()

        self.sphS_log_label = QtWidgets.QLabel(parent=self.sphericalSTab)

        self.sphS_log_label.setStyleSheet("font-weight: bold")
        self.sphS_log_VLayout.addWidget(self.sphS_log_label)
        self.sphS_log_textEdit = QtWidgets.QTextEdit(parent=self.sphericalSTab)
        self.sphS_log_textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sphS_log_VLayout.addWidget(self.sphS_log_textEdit)
        self.sphS_run_HLayout.addLayout(self.sphS_log_VLayout)
        self.sphS_VLayout.addLayout(self.sphS_run_HLayout)
        self.sphS_VLayout.setStretch(0, 1)
        self.sphS_VLayout.setStretch(2, 1)
        self.sphS_VLayout.setStretch(4, 1)
        self.gridLayout_5.addLayout(self.sphS_VLayout, 0, 0, 1, 1)
        self.mainTabWidget.addTab(self.sphericalSTab, "")
        self.mainGridLayout.addWidget(self.mainTabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.mainGridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1624, 22))
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        MainWindow.setStatusBar(self.statusbar)
        self.tracesDockWidget = QtWidgets.QDockWidget(parent=MainWindow)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.button_step = QtWidgets.QPushButton(parent=self.dockWidgetContents)
        self.gridLayout.addWidget(self.button_step, 3, 0, 1, 1)
        self.button_update_continuous = QtWidgets.QPushButton(parent=self.dockWidgetContents)
        self.gridLayout.addWidget(self.button_update_continuous, 3, 1, 1, 1)
        self.traces_to_show = QtWidgets.QComboBox(parent=self.dockWidgetContents)
        self.gridLayout.addWidget(self.traces_to_show, 1, 0, 1, 2)
        self.plotPlaceholderWidget_1 = self.canvas
        self.gridLayout.addWidget(self.plotPlaceholderWidget_1, 0, 0, 1, 2)
        self.tracesDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.tracesDockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(parent=MainWindow)
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.widget_2 = QtWidgets.QWidget(parent=self.dockWidgetContents_2)
        self.gridLayout_8.addWidget(self.widget_2, 0, 0, 1, 3)
        self.coordinat_slider = QtWidgets.QSlider(parent=self.dockWidgetContents_2)
        self.coordinat_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.gridLayout_8.addWidget(self.coordinat_slider, 3, 2, 1, 1)
        self.combobox_plot_format = QtWidgets.QComboBox(parent=self.dockWidgetContents_2)
        self.gridLayout_8.addWidget(self.combobox_plot_format, 1, 0, 1, 2)
        self.checkbox_scatter = QtWidgets.QRadioButton(parent=self.dockWidgetContents_2)
        self.gridLayout_8.addWidget(self.checkbox_scatter, 1, 2, 1, 1)
        self.coordinate_label = QtWidgets.QLabel(parent=self.dockWidgetContents_2)
        self.gridLayout_8.addWidget(self.coordinate_label, 3, 0, 1, 1)
        self.textfield_frequency_label = QtWidgets.QLabel(parent=self.dockWidgetContents_2)
        self.gridLayout_8.addWidget(self.textfield_frequency_label, 2, 0, 1, 1)
        self.textfield_frequency_slider = QtWidgets.QSlider(parent=self.dockWidgetContents_2)
        self.textfield_frequency_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.gridLayout_8.addWidget(self.textfield_frequency_slider, 2, 2, 1, 1)
        self.textfield_frequency = QtWidgets.QLineEdit(parent=self.dockWidgetContents_2)
        self.gridLayout_8.addWidget(self.textfield_frequency, 2, 1, 1, 1)
        self.coordinate = QtWidgets.QLineEdit(parent=self.dockWidgetContents_2)
        self.gridLayout_8.addWidget(self.coordinate, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()

        self.button_save_current_points = QtWidgets.QPushButton(parent=self.dockWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.button_save_current_points)
        self.button_save_all_points_at_frequency = QtWidgets.QPushButton(parent=self.dockWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.button_save_all_points_at_frequency)
        self.button_save_all_points = QtWidgets.QPushButton(parent=self.dockWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.button_save_all_points)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 4, 0, 1, 3)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)
        self.actionReset = QtGui.QAction(parent=MainWindow)
        self.actionClose = QtGui.QAction(parent=MainWindow)
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.menuSettings.addAction(self.actionReset)
        self.menuSettings.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cont_vna_pushButton.setText(_translate("MainWindow", "Connect VNA"))
        self.ping_robot_pushButton.setText(_translate("MainWindow", "Ping Robot"))
        self.robot_ip_label.setText(_translate("MainWindow", "Robot IP"))
        self.con_robot_pushButton.setText(_translate("MainWindow", "Connect Robot"))
        self.con_stop_pushButton.setText(_translate("MainWindow", "STOP"))
        self.vna_ip_label.setText(_translate("MainWindow", "VNA IP"))
        self.vna_port_label.setText(_translate("MainWindow", "VNA Port"))
        self.ping_vna_pushButton.setText(_translate("MainWindow", "Ping VNA"))
        self.disconnect_pushButton.setText(_translate("MainWindow", "Disconnect"))
        self.robot_port_label.setText(_translate("MainWindow", "Robot Port"))
        self.con_log_header_label.setText(_translate("MainWindow", "Log Information"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.connectionTab), _translate("MainWindow", "Connection"))
        self.man_stop_pushButton.setText(_translate("MainWindow", "STOP"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.manualCTab), _translate("MainWindow", "Manual Control"))
        self.xyzS_params_label.setText(_translate("MainWindow", "Scan Parameters"))
        self.x0_xyzS_label.setText(_translate("MainWindow", "X0"))
        self.xmin_xyzS_label.setText(_translate("MainWindow", "Xmin"))
        self.xmax_xyzS_label.setText(_translate("MainWindow", "Xmax"))
        self.zmax_xyzS_label.setText(_translate("MainWindow", "Zmax"))
        self.xz0_xyzS_label.setText(_translate("MainWindow", "Z0"))
        self.ymin_xyzS_label.setText(_translate("MainWindow", "Ymin"))
        self.ymax_xyzS_label.setText(_translate("MainWindow", "Ymax"))
        self.ystp_xyzS_label.setText(_translate("MainWindow", "sY"))
        self.xy0_xyzS_label.setText(_translate("MainWindow", "Y0"))
        self.xstp_xyzS_label.setText(_translate("MainWindow", "sX"))
        self.zmin_xyzS_label.setText(_translate("MainWindow", "Zmin"))
        self.zstp_xyzS_label.setText(_translate("MainWindow", "sZ"))
        self.a0_xyzS_label.setText(_translate("MainWindow", "A0"))
        self.b0_xyzS_label.setText(_translate("MainWindow", "B0"))
        self.c0_xyzS_label.setText(_translate("MainWindow", "C0"))
        self.xyzS_datapath_label.setText(_translate("MainWindow", "Data File"))
        self.xpol_xyzS_params_checkBox.setText(_translate("MainWindow", "X-Pol"))
        self.xyzS_datapath_toolButton.setText(_translate("MainWindow", "..."))
        self.xyzS_vna_label.setText(_translate("MainWindow", "VNA Parameters"))
        self.ifbw_xyzS_vna_label.setText(_translate("MainWindow", "IF BW"))
        self.ab_xyzS_vna_checkBox.setText(_translate("MainWindow", "A/B"))
        self.sttl_xyzS_vna_label.setText(_translate("MainWindow", "Settling Time"))
        self.attn_xyzS_vna_label.setText(_translate("MainWindow", "Attenuation"))
        self.fmin_xyzS_vna_label.setText(_translate("MainWindow", "f min"))
        self.fmax_xyzS_vna_label.setText(_translate("MainWindow", "f max"))
        self.xyzS_vna_pushButton.setText(_translate("MainWindow", "Send to VNA"))
        self.fwbw_xyzS_vna_checkBox.setText(_translate("MainWindow", "FW/BW"))
        self.fstp_xyzS_vna_label.setText(_translate("MainWindow", "sf"))
        self.xyzS_run_pushButton.setText(_translate("MainWindow", "Run"))
        self.xyzS_sim_pushButton.setText(_translate("MainWindow", "Simulate"))
        self.xyzS_stop_pushButton.setText(_translate("MainWindow", "STOP"))
        self.xyzS_run_label.setText(_translate("MainWindow", "Start/Stop"))
        self.xyzS_fdbk_label.setText(_translate("MainWindow", "Live feedback position"))
        self.z_xyzS_fdbk_label.setText(_translate("MainWindow", "Z"))
        self.c_xyzS_fdbk_val_label.setText(_translate("MainWindow", "Cval"))
        self.y_xyzS_fdbk_val_label.setText(_translate("MainWindow", "Yval"))
        self.c_xyzS_fdbk_label.setText(_translate("MainWindow", "C"))
        self.x_xyzS_fdbk_label.setText(_translate("MainWindow", "X"))
        self.z_xyzS_fdbk_val_label.setText(_translate("MainWindow", "Zval"))
        self.y_xyzS_fdbk_label.setText(_translate("MainWindow", "Y"))
        self.b_xyzS_fdbk_label.setText(_translate("MainWindow", "B"))
        self.a_xyzS_fdbk_val_label.setText(_translate("MainWindow", "Aval"))
        self.a_xyzS_fdbk_label.setText(_translate("MainWindow", "A"))
        self.b_xyzS_fdbk_val_label.setText(_translate("MainWindow", "Bval"))
        self.x_xyzS_fdbk_val_label.setText(_translate("MainWindow", "Xval"))
        self.xyzS_log_label.setText(_translate("MainWindow", "Log"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.xyzSTab), _translate("MainWindow", "XYZ Scan"))
        self.sphS_params_label.setText(_translate("MainWindow", "Scan Parameters"))
        self.yc_sphS_label.setText(_translate("MainWindow", "YC"))
        self.phstp_sphS_label.setText(_translate("MainWindow", "sφ"))
        self.a0_sphS_label.setText(_translate("MainWindow", "A0"))
        self.r_sphS_label.setText(_translate("MainWindow", "R"))
        self.b0_sphS_label.setText(_translate("MainWindow", "B0"))
        self.thmin_sphS_label.setText(_translate("MainWindow", "θmin"))
        self.c0_sphS_label.setText(_translate("MainWindow", "C0"))
        self.thmax_sphS_label.setText(_translate("MainWindow", "θmax"))
        self.zc_sphS_label.setText(_translate("MainWindow", "ZC"))
        self.xc_sphS_label.setText(_translate("MainWindow", "XC"))
        self.phmin_sphS_label.setText(_translate("MainWindow", "φmin"))
        self.phmax_sphS_label.setText(_translate("MainWindow", "φmax"))
        self.thstp_sphS_label.setText(_translate("MainWindow", "sθ"))
        self.sphS_datapath_label.setText(_translate("MainWindow", "Data File"))
        self.xpol_sphS_params_checkBox_2.setText(_translate("MainWindow", "X-Pol"))
        self.sphS_datapath_toolButton.setText(_translate("MainWindow", "..."))
        self.sphS_vna_label.setText(_translate("MainWindow", "VNA Parameters"))
        self.ab_sphS_vna_checkBox.setText(_translate("MainWindow", "A/B"))
        self.fwbw_sphS_vna_checkBox.setText(_translate("MainWindow", "FW/BW"))
        self.fmin_sphS_vna_label.setText(_translate("MainWindow", "f min"))
        self.fmax_sphS_vna_label.setText(_translate("MainWindow", "f max"))
        self.fstp_sphS_vna_label.setText(_translate("MainWindow", "sf"))
        self.sphS_vna_pushButton.setText(_translate("MainWindow", "Send to VNA"))
        self.ifbw_sphS_vna_label.setText(_translate("MainWindow", "IF BW"))
        self.attn_sphS_vna_label.setText(_translate("MainWindow", "Attenuation"))
        self.sttln_sphS_vna_label.setText(_translate("MainWindow", "Settling Time"))
        self.sphS_run_pushButton.setText(_translate("MainWindow", "Run"))
        self.sphS_sim_pushButton.setText(_translate("MainWindow", "Simulate"))
        self.sphS_stop_pushButton.setText(_translate("MainWindow", "STOP"))
        self.sphS_run_label.setText(_translate("MainWindow", "Start/Stop"))
        self.sphS_fdbk_label.setText(_translate("MainWindow", "Live feedback position"))
        self.y_sphS_fdbk_val_label.setText(_translate("MainWindow", "Yval"))
        self.x_sphS_fdbk_val_label.setText(_translate("MainWindow", "Xval"))
        self.x_sphS_fdbk_label.setText(_translate("MainWindow", "X"))
        self.a_sphS_fdbk_label.setText(_translate("MainWindow", "A"))
        self.b_sphS_fdbk_val_label.setText(_translate("MainWindow", "Bval"))
        self.z_sphS_fdbk_val_label.setText(_translate("MainWindow", "Zval"))
        self.b_sphS_fdbk_label.setText(_translate("MainWindow", "B"))
        self.c_sphS_fdbk_label.setText(_translate("MainWindow", "C"))
        self.z_sphS_fdbk_label.setText(_translate("MainWindow", "Z"))
        self.c_sphS_fdbk_val_label.setText(_translate("MainWindow", "Cval"))
        self.a_sphS_fdbk_val_label.setText(_translate("MainWindow", "Aval"))
        self.y_sphS_fdbk_label.setText(_translate("MainWindow", "Y"))
        self.r_sphS_fdbk_label.setText(_translate("MainWindow", "R"))
        self.r_sphS_fdbk_val_label.setText(_translate("MainWindow", "Rval"))
        self.th_sphS_fdbk_label.setText(_translate("MainWindow", "θ"))
        self.th_sphS_fdbk_val_label.setText(_translate("MainWindow", "θval"))
        self.ph_sphS_fdbk_val_label.setText(_translate("MainWindow", "φval"))
        self.ph_sphS_fdbk_label.setText(_translate("MainWindow", "φ"))
        self.sphS_log_label.setText(_translate("MainWindow", "Log"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.sphericalSTab), _translate("MainWindow", "Spherical Scan"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.tracesDockWidget.setWindowTitle(_translate("MainWindow", "VNA traces"))
        self.button_step.setText(_translate("MainWindow", "Plot"))
        self.button_update_continuous.setText(_translate("MainWindow", "Step"))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "Scanned points"))
        self.checkbox_scatter.setText(_translate("MainWindow", "RadioButton"))
        self.coordinate_label.setText(_translate("MainWindow", "Change coordinate to (mm):"))
        self.textfield_frequency_label.setText(_translate("MainWindow", "Change frequency to (GHz):"))
        self.button_save_current_points.setText(_translate("MainWindow", "Save current slice as .txt"))
        self.button_save_all_points_at_frequency.setText(_translate("MainWindow", "Save all points at current frequency as .txt"))
        self.button_save_all_points.setText(_translate("MainWindow", "Save all points as .txt"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

if __name__ == '__main__':
    if not QtWidgets.QApplication.instance():
        app = QtWidgets.QApplication(sys.argv)
    else:
        app = QtWidgets.QApplication.instance()
    window = MainWindow()
    window.show()
    sys.exit(app.exec())